[package]
name = "wizardrs-client"
version = "0.1.0"
edition = "2021"

[dependencies]
wizardrs-core = { path = "../wizardrs-core"}
wizardrs-server = { path = "../wizardrs-server"}
tokio = { version = "1.0.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-tungstenite = "0.24.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
serde_json = "1.0.133"
futures = "0.3.31"
derive_more = "1.0.0"
thiserror = "2.0.3"
uuid = { version = "1.11.0", features = ["v4"] }
egui = "0.29.1"
eframe = "0.29.1"
strum = { version = "0.26.3", features = ["derive"] }
arboard = "3.4.1"
