on:
  release:
    types: [created]

jobs:
  release:
    name: Release - ${{ matrix.platform.os-name }}
    continue-on-error: true
    strategy:
      matrix:
        platform:
          - os-name: x86_64-pc-windows-msvc
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: x86_64-pc-windows-gnu
            runs-on: windows-latest
            target: x86_64-pc-windows-gnu

          - os-name: x86_64-apple-darwin
            runs-on: macOS-latest
            target: x86_64-apple-darwin

          - os-name: x86_64-unknown-linux-musl
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl

          - os-name: aarch64-unknown-linux-musl
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl

          - os-name: x86_64-unknown-linux-gnu
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: false
          working-directory: 'wizardrs-client'
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: 'wizardrs-client'
          target: ${{ matrix.platform.target }}
          working-directory: 'wizardrs-client'
          changes-file: ''
