on:
  release:
    types: [created]
permissions:
  contents: write
env:
  RUST_BACKTRACE: 1
  CACHE_ON_FAILURE: true
jobs:
  generate-changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate CHANGELOG.md
        uses: orhun/git-cliff-action@v2
        with:
          config: 'cliff.toml'
          args: '--verbose'
        env:
          OUTPUT: CHANGELOG.md

      - name: Commit CHANGELOG.md
        run: |
          git checkout master
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "chore: update Changelog"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/TgZ39/wizardrs.git master

  release:
    name: Release - ${{ matrix.platform.os-name }}
    needs: generate-changelog
    strategy:
      matrix:
        platform:
          - os-name: x86_64-pc-windows-msvc
            runs-on: windows-latest
            target: x86_64-pc-windows-msvc

          - os-name: x86_64-pc-windows-gnu
            runs-on: windows-latest
            target: x86_64-pc-windows-gnu

          - os-name: x86_64-apple-darwin
            runs-on: macOS-latest
            target: x86_64-apple-darwin

          - os-name: x86_64-unknown-linux-musl
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-musl

          - os-name: aarch64-unknown-linux-musl
            runs-on: ubuntu-20.04
            target: aarch64-unknown-linux-musl

          - os-name: x86_64-unknown-linux-gnu
            runs-on: ubuntu-20.04
            target: x86_64-unknown-linux-gnu

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: 'build'
          target: ${{ matrix.platform.target }}
          args: '--locked --release'
          strip: true
      - name: Publish artifacts and release
        uses: houseabsolute/actions-rust-release@v0
        with:
          executable-name: 'wizardrs-client'
          target: ${{ matrix.platform.target }}
          changes-file: 'CHANGELOG.md'
