[package]
name = "wizardrs-core"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0"
derive_more = { version = "1.0", features = ["display"] }
strum = { version = "0.26", features = ["derive"] }

[dev-dependencies]
paste = "1.0"